spring:
  rabbitmq:
    host: 192.168.1.241
    port: 5672
    username: guest
    password: guest
 
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  #开启重试功能
  retryable: true
  routes:
    service:
      path: /test/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: cloudplatform-service-local
      retryable: true
    auth:
      path: /auth/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: cloudplatform-auth-local
    user:
      path: /user/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: cloudplatform-user-local
security:
  basic:
    enabled: false
  oauth2:
    client:
#     client-id: webApp
#     client-secret: webApp
      access-token-uri: http://127.0.0.1:9091/auth/oauth/token    #网关的地址
      user-authorization-uri: http://127.0.0.1:9091/auth/oauth/authorize
    resource:
      user-info-uri:  http://127.0.0.1:9092/user
      prefer-token-info: false

      
ribbon:
  connectTimeout: 500
  ReadTimeout: 2000
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #切换到相同Server的次数
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000
#启动feign熔断器功能
feign:
  hystrix:
    enabled: true