spring:
  rabbitmq:
    host: 192.168.1.241
    port: 5672
    username: guest
    password: guest
 
zuul:
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
  retryable: true
  routes:
    service:
      path: /test/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: cloudplatform-service-local
      retryable: true
    auth:
      path: /auth/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: cloudplatform-auth-local
    user:
      path: /user/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: cloudplatform-user-local
security:
  basic:
    enabled: false
  oauth2:
    client:
#     client-id: webApp
#     client-secret: webApp
      access-token-uri: http://127.0.0.1:9091/auth/oauth/token    #网关的地址
      user-authorization-uri: http://127.0.0.1:9091/auth/oauth/authorize
    resource:
      user-info-uri:  http://127.0.0.1:9092/user
      prefer-token-info: false

cloudplatform-service-local:    
  ribbon:
    connectTimeout: 500
    readTimeout: 2000
      #同一个Server重试的次数(除去首次)
    MaxAutoRetries: 2
      #切换到相同Server的次数
    MaxAutoRetriesNextServer: 0
    okToRetryOnAllOperations: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
#启动feign熔断器功能
feign:
  hystrix:
    enabled: true